pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=CI tests / clojure-deps (pull_request)
    actions:
      merge:
        method: merge
        

  - name: automatic merge for deps.edn pull requests
    conditions:
      - author=github-actions[bot]
      - check-success~=CI
    actions:
      merge:
        method: merge