name: "CI tests"

on:
  pull_request:
  push:

jobs:
  clojure-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: latest

      - name: Test
        run: |
          clojure -e "((requiring-resolve 'local-utils/init) {:nrepl false}) (keys (ns-publics '.))"
