on:
  schedule:
    - cron: "1 5 * * 2"

jobs:
  clojure-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest

      - name: Update clj dependencies
        run:
          clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version
          "RELEASE"}}}' -M -m antq.core --upgrade --force

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
          commit-message: Update clojure dependencies
          title: Update clojure dependencies
          assignees: jlesquembre
          branch: update-clj-deps
