on:
  schedule:
    - cron: "1 5 * * 2"

jobs:
  clojure-deps:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: DeLaGuardo/setup-clojure@8.0
        with:
          cli: latest

      - name: Update clj dependencies
        run:
          clojure -Sdeps '{:deps {com.github.liquidz/antq {:mvn/version
          "RELEASE"}}}' -M -m antq.core -d dotfiles/clojure --upgrade --force
          --skip=github-action

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          commit-message: Update clojure dependencies
          title: Update clojure dependencies
          assignees: jlesquembre
          branch: update-clj-deps
